---
language: php
dist: trusty

# Use the lowest version of PHP supported by Acquia.
php: 7.1

addons:
  # ChromeDriver is used for PHPUnit tests.
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$TMPDIR/phpstan/cache"

# Execution time is drastically reduced by splitting the build into multiple
# concurrent jobs.
matrix:
  # Mark the build as finished as soon as the only remaining jobs are allowed to
  # fail.
  fast_finish: true
  include:
    - { name: "Static code analysis", env: ORCA_JOB=STATIC_CODE_ANALYSIS }
    - { name: "Deprecated code scan w/ SUT", env: ORCA_JOB=DEPRECATED_CODE_SCAN_SUT }
    - { name: "Deprecated code scan w/ dependencies", env: ORCA_JOB=DEPRECATED_CODE_SCAN_CONTRIB }
    - { name: "Isolated test w/ recommended package versions", env: ORCA_JOB=ISOLATED_RECOMMENDED }
    - { name: "Integrated test w/ recommended package versions", env: ORCA_JOB=INTEGRATED_RECOMMENDED }
    - { name: "Isolated test w/ dev package versions", env: ORCA_JOB=ISOLATED_DEV }
    - { name: "Integrated test w/ dev package versions", env: ORCA_JOB=INTEGRATED_DEV }
  allow_failures:
    - env: ORCA_JOB=DEPRECATED_CODE_SCAN_SUT
    - env: ORCA_JOB=DEPRECATED_CODE_SCAN_CONTRIB
    - env: ORCA_JOB=ISOLATED_DEV
    - env: ORCA_JOB=INTEGRATED_DEV

install:
  - "git clone --depth 1 https://github.com/acquia/orca.git ../orca"
  # Install ORCA and prepare the environment.
  # Supply the topic branch of the SUT to help Composer guess its version.
  - "../orca/bin/travis/install 8.x-1.x"

# Run test script.
# Supply the package name of the SUT.
script: "../orca/bin/travis/script drupal/example"
