---
language: php
dist: trusty

# Use the lowest version of PHP supported by Acquia.
php: 7.1

addons:
  # ChromeDriver is used for PHPUnit tests.
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

# Execution time is drastically reduced by splitting the build into multiple
# concurrent threads.
matrix:
  include:
    - name: "Static analysis"
      env: ORCA_FIXTURE=none
    - name: "Isolated test"
      env: ORCA_FIXTURE=sut-only
    - name: "Integrated test"
      env: ORCA_FIXTURE=standard

install:
  - "git clone --depth 1 git@github.com:acquia/orca.git ../orca"
  # Install ORCA and prepare the environment.
  # Supply the topic branch of the SUT to help Composer guess its version.
  - "../orca/bin/travis/install 8.x-1.x"

# Run test script.
# Supply the package name of the SUT.
script: "../orca/bin/travis/script drupal/example"
