---
language: php
dist: trusty

# Use the lowest version of PHP supported by Acquia.
php: 7.1

addons:
  # ChromeDriver is used for PHPUnit tests.
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

# Execution time is drastically reduced by splitting the build into multiple
# concurrent jobs.
matrix:
  include:
    - name: "Static code analysis"
      env: ORCA_FIXTURE=none
    - name: "Isolated test w/ recommended package versions"
      env: ORCA_FIXTURE=sut-only ORCA_PACKAGE_STABILITY=stable
    - name: "Integrated test w/ recommended package versions"
      env: ORCA_FIXTURE=standard ORCA_PACKAGE_STABILITY=stable
    - name: "Isolated test w/ dev package versions"
      env: ORCA_FIXTURE=sut-only ORCA_PACKAGE_STABILITY=dev
    - name: "Integrated test w/ dev package versions"
      env: ORCA_FIXTURE=standard ORCA_PACKAGE_STABILITY=dev
  allow_failures:
    - env: ORCA_FIXTURE=sut-only ORCA_PACKAGE_STABILITY=dev
    - env: ORCA_FIXTURE=standard ORCA_PACKAGE_STABILITY=dev

install:
  - "git clone --depth 1 https://github.com/acquia/orca.git ../orca"
  # Install ORCA and prepare the environment.
  - ../orca/bin/travis/install

# Run test script.
# Supply the package name of the SUT.
script: "../orca/bin/travis/script drupal/example"
