# Example Travis CI configuration.
#
# This configuration file will cover ORCA integration for most packages almost
# without modification. Use as follows:
#
# 1. Copy this file to your package root:
#
#    $ cp example/.travis.yml ../my_package/.travis.yml
#
# 2. Change the values in env.global for your package. No other changes are
#    strictly necessary for a basic integration.
#
# 3. Strip the (now unnecessary) comments:
#
#    $ grep -v '^ *#' .travis.yml > .travis.yml
#
# For advanced needs,
# @see https://github.com/acquia/orca/blob/develop/docs/advanced-usage.md
---
language: php

# The lowest version of PHP supported by Acquia.
php: 7.1

addons:
  # ChromeDriver is used for PHPUnit tests.
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$TMPDIR/phpstan/cache"

env:
  # Change the following values for your implementation.
  global:
    # Provide your package's name.
    - ORCA_SUT_NAME=drupal/example
    # Specify the name of the nearest Git version branch, e.g., 1.x or 8.x-1.x.
    # This may be the destination branch of a pull request or the nearest
    # ancestor of a topic branch.
    - ORCA_SUT_BRANCH=8.x-1.x
    # Specify the version of ORCA to use. Use the master branch for the latest
    # release, develop for Dev/HEAD, or a tag name (e.g., v1.0.0) for a specific
    # release.
    - ORCA_VERSION=master

# Execution time is drastically reduced by splitting the build into multiple
# concurrent jobs.
matrix:
  # Mark the build as finished once the only remaining jobs are allowed to fail.
  fast_finish: true
  include:
    - { name: "Static code analysis", env: ORCA_JOB=STATIC_CODE_ANALYSIS }
    - { name: "Deprecated code scan w/ SUT", env: ORCA_JOB=DEPRECATED_CODE_SCAN_SUT }
    - { name: "Deprecated code scan w/ dependencies", env: ORCA_JOB=DEPRECATED_CODE_SCAN_CONTRIB }
    - { name: "Isolated test w/ recommended package versions", env: ORCA_JOB=ISOLATED_RECOMMENDED }
    - { name: "Integrated test w/ recommended package versions", env: ORCA_JOB=INTEGRATED_RECOMMENDED }
    - { name: "Previous minor version of Drupal core", env: ORCA_JOB=CORE_PREVIOUS }
    - { name: "Isolated test w/ dev package versions", env: ORCA_JOB=ISOLATED_DEV }
    - { name: "Integrated test w/ dev package versions", env: ORCA_JOB=INTEGRATED_DEV }
    - { name: "Next pre-release of Drupal core", env: ORCA_JOB=CORE_NEXT }
  # For various reasons, some jobs are allowed to fail without failing the whole
  # build. They should still be watched for advance notice of future problems.
  # @see https://docs.travis-ci.com/user/customizing-the-build#rows-that-are-allowed-to-fail
  allow_failures:
    # Obviously, issues in third party code should not fail a build.
    - env: ORCA_JOB=DEPRECATED_CODE_SCAN_CONTRIB
    # Dev jobs are allowed to fail due to their inherent instability.
    - env: ORCA_JOB=ISOLATED_DEV
    - env: ORCA_JOB=INTEGRATED_DEV

# Install ORCA and prepare the environment.
before_install:
  - git clone --branch ${ORCA_VERSION} --depth 1 https://github.com/acquia/orca.git ../orca
  - ../orca/bin/travis/before_install.sh

# Create the test fixture and place the SUT.
install: ../orca/bin/travis/install.sh

# Run the test script.
script: ../orca/bin/travis/script.sh

# Display debugging information in case of failure.
after_failure: ../orca/bin/travis/after_failure.sh
