---
language: php
dist: trusty

php: 7.1

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

git:
  quiet: true

branches:
  only:
    - master
    - develop
    - wip

matrix:
  include:
    - name: "Static analysis and unit tests"
      env: ORCA_FIXTURE=none
    - name: "Isolated test w/ recommended package versions"
      env: ORCA_FIXTURE=sut-only ORCA_PACKAGE_STABILITY=stable
    - name: "Integrated test w/ recommended package versions"
      env: ORCA_FIXTURE=standard ORCA_PACKAGE_STABILITY=stable
    - name: "Isolated test w/ dev package versions"
      env: ORCA_FIXTURE=sut-only ORCA_PACKAGE_STABILITY=dev
    - name: "Integrated test w/ dev package versions"
      env: ORCA_FIXTURE=standard ORCA_PACKAGE_STABILITY=dev
    - name: "Live product test w/ recommended versions of all packages"
      env: ORCA_LIVE=true
  allow_failures:
    - env: ORCA_LIVE=true

install: "./bin/travis/install master"

script: "[[ -z \"$ORCA_LIVE\" ]] && ./bin/self-test || ./bin/live-test"
