---
language: php
dist: trusty

php: 7.1

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

git:
  depth: 1
  quiet: true

branches:
  only:
    - master
    - develop
    - wip

matrix:
  include:
    - name: "Static analysis and unit tests"
      env: ORCA_FIXTURE=none
    - name: "Isolated test"
      env: ORCA_FIXTURE=sut-only
    - name: "Integrated test"
      env: ORCA_FIXTURE=standard

install: ./bin/travis/install

script: ./bin/self-test
