---
-
  name: acquia/acsf-tools
  type: drupal-drush
-
  name: acquia/drupal-spec-tool
  type: behat-extension
#-
#  name: drupal/acquia_commercemanager
#  url: ../commerce-manager
#-
#  name: drupal/acquia_connector
#  url: ../acquia-connector
#-
#  name: drupal/acquia_contenthub
#  url: ../content-hub-d8
#  version: ~1.0
#-
#  name: drupal/acquia_lift
-
  name: drupal/acquia_purge
#-
#  name: drupal/acsf
-
  name: drupal/cog
  type: drupal-theme
-
  name: drupal/lightning_api
  url: ../lightning-api
-
  name: drupal/lightning_core
  url: ../lightning-core
-
  name: drupal/lightning_layout
  url: ../lightning-layout
-
  name: drupal/lightning_media
  url: ../lightning-media
-
  name: drupal/lightning_workflow
  url: ../lightning-workflow
#-
#  name: drupal/media_acquiadam
