---
# An indexed array of Acquia software package data. Each element is an
# associative array that may contain the following key-value pairs:
# - "name": (required) The package name, corresponding to the "name" property in
#   its composer.json file, e.g., "drupal/example".
# - "type": (optional) The package type, corresponding to the "type" property in
#   its composer.json file. Defaults to "drupal-module".
# - "install_path": (optional) The path the package gets installed at relative
#   to the fixture root, e.g., docroot/modules/contrib/example.
#   Used internally for Drupal submodules. Defaults by "type" to match the
#   "installer-paths" patterns specified by BLT.
# - "url": (optional) The path, absolute or relative to the fixture root, of a
#   local clone of the package. Used for the "url" property of the
#   Composer path repository used to symlink the system under test (SUT) into
#   place. Defaults to a directory adjacent to the fixture root named the
#   Composer project name, e.g., "../example" for a "drupal/example" project.
# - "version": (optional) The package version to require via Composer. Defaults
#   to "*".
#
# These are converted to \Acquia\Orca\Fixture\Package objects by
# \Acquia\Orca\Fixture\PackageManager. A different specification can be
# substituted at runtime using the "ORCA_PACKAGES_CONFIG" environment variable.
# See config/services.yml for the relevant code or bin/self-test for a usage
# example.
-
  name: acquia/acsf-tools
  type: drupal-drush
  # acsf-tools specifies an installer-name.
  install_path: drush/Commands/acsf_tools
-
  name: acquia/drupal-spec-tool
  type: behat-extension
#-
#  name: drupal/acquia_commercemanager
#  url: ../commerce-manager
#-
#  name: drupal/acquia_connector
#  url: ../acquia-connector
#-
#  name: drupal/acquia_contenthub
#  url: ../content-hub-d8
#  version: ~1.0
#-
#  name: drupal/acquia_lift
-
  name: drupal/acquia_purge
#-
#  name: drupal/acsf
-
  name: drupal/cog
  type: drupal-theme
-
  name: drupal/lightning_api
  url: ../lightning-api
-
  name: drupal/lightning_core
  url: ../lightning-core
-
  name: drupal/lightning_layout
  url: ../lightning-layout
-
  name: drupal/lightning_media
  url: ../lightning-media
-
  name: drupal/lightning_workflow
  url: ../lightning-workflow
#-
#  name: drupal/media_acquiadam
