parameters:

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Acquia\Orca\:
    resource: '../src'
    public: false

  Symfony\Component\Console\Application:

  Symfony\Component\Console\Input\ArgvInput:

  Symfony\Component\Console\Output\ConsoleOutput:

  Symfony\Component\Console\Style\SymfonyStyle:
    arguments:
    - '@Symfony\Component\Console\Input\ArgvInput'
    - '@Symfony\Component\Console\Output\ConsoleOutput'

  Symfony\Component\Filesystem\Filesystem:

  Symfony\Component\Process\ExecutableFinder:
