---
parameters:
  env(ORCA_PROJECTS_CONFIG): "config/projects.yml"

services:

  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      $fixture_dir: "%app.fixture_dir%"
      $project_dir: "%kernel.project_dir%"
      $projects_config: "%env(ORCA_PROJECTS_CONFIG)%"
    public: true

  Acquia\Orca\:
    exclude: ../src/Kernel.php
    public: false
    resource: ../src

  Symfony\Component\Console\Application: ~

  Symfony\Component\Console\Input\ArgvInput: ~

  Symfony\Component\Console\Input\InputInterface:
    alias: Symfony\Component\Console\Input\ArgvInput

  Symfony\Component\Console\Output\ConsoleOutput: ~

  Symfony\Component\Console\Output\OutputInterface:
    alias: Symfony\Component\Console\Output\ConsoleOutput

  Symfony\Component\Console\Style\SymfonyStyle: ~

  Symfony\Component\Filesystem\Filesystem: ~

  Symfony\Component\Finder\Finder: ~

  Symfony\Component\Process\ExecutableFinder: ~

  Symfony\Component\Yaml\Parser: ~
