parameters:

services:

  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $cache_dir: '%kernel.cache_dir%'
    public: true

  Acquia\Orca\:
    resource: '../src'
    exclude: '../src/Kernel.php'
    public: false

  Symfony\Component\Console\Application:

  Symfony\Component\Console\Input\ArgvInput:

  Symfony\Component\Console\Output\ConsoleOutput:

  Symfony\Component\Console\Style\SymfonyStyle:
    arguments:
      $input: '@Symfony\Component\Console\Input\ArgvInput'
      $output: '@Symfony\Component\Console\Output\ConsoleOutput'

  Symfony\Component\Filesystem\Filesystem:

  Symfony\Component\Process\ExecutableFinder:
