# Example Travis CI configuration for a drupal/example package.

language: php
dist: trusty

php: 7.1

addons:
  chrome: stable

before_install:
  - git clone git@github.com:acquia/orca.git ../orca
  - ../orca/bin/travis/before_install

script: ../orca/bin/travis/script drupal/example
