# Example Travis CI configuration for a drupal/example package.
---
language: php
dist: trusty

php: 7.1

addons:
  chrome: stable

before_install: git clone --depth 1 git@github.com:acquia/orca.git ../orca

install: ../orca/bin/travis/install

script: ../orca/bin/travis/script drupal/example
